#!/usr/bin/env ruby
# encoding: UTF-8
=begin
Copyright Daniel Meißner <dm@3st.be>, 2011

This file is part of a HAVPVirusDetectionsMuninPlugin script to show virus detections, logged by HAVP.

This script is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This Script is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with HAVPVirusDetectionsMuninPlugin.  If not, see <http://www.gnu.org/licenses/>.
=end

def show_config
  puts 'graph_title HAVP virus detections'
  puts 'graph_category proxy'
  puts 'graph_info This graph shows virus detections logged by HAVP'
  puts 'graph_vlabel Viruses'
  puts 'graph_scale yes'
  puts 'graph_period count'
  puts 'virus_detections.label virus_detections'
end

def count_viruses
  virus_count = 0

  File.open('/var/log/havp/access.log').each_line do |line|
    next if not line =~ /VIRUS/
    virus_count += 1
  end

  puts "virus_detections.value #{virus_count}"
end

begin
  if ARGV[0] == "config"
    show_config
  else
    count_viruses
  end
end